# Generated by Django 5.1 on 2024-08-17 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data_load',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
