# Generated by Django 5.1 on 2024-08-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika_web', '0003_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='report',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
