# Generated by Django 5.1 on 2024-08-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistika_web', '0004_order_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='report',
        ),
        migrations.AddField(
            model_name='order',
            name='interest_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('морской', 'Морской'), ('авиа', 'Авиа'), ('железнодорожный', 'Железнодорожный'), ('автоперевозки', 'Автоперевозки'), ('сборный', 'Сборный'), ('мультимодальные', 'Мультимодальные')], default='морской', max_length=30, null=True),
        ),
    ]
